config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'bookings#dashboard', as: :dashboard
  resources :paintings do
    resources :bookings, only: [:create, :new]
  end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
require 'date'
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :painting

  validates :start_date, :end_date, presence: true
  # validates the starting date is not later than the end date
  validates :end_date_after_start_date, presence: true
  # validates :date_after_today, presence: true

  def booked_date_range
    { from: :start_date, to: :end_date }
  end

  def set_booking_number
    Self.booking_number = "MAMA" + '- ' + SecureRandom.hex(4).upcase
  end

  private

  def end_date_after_start_date
    return false if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, 'The end date must be after the start date')
    else
      return true
    end
  end

    # def date_after_today
    #   if Date.today > :start_date
    #     return false
    #   else
    #     errors.add('The date cannot be before today')
    #   end
    # end
end

app/models/painting.rb
class Painting < ApplicationRecord
  has_many :users
  validates :title, :category, :price, :image, presence: true
  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :paintings
  # validates :first_name, :last_name, :username, presence: true
  # validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :authenticate_user!

  def new
    @painting = Painting.find(params[:painting_id])
    @booking = @painting.bookings.new(quantity: params[:quantity])
    @booking.user = current_user
  end

  def dashboard
    # index
    @bookings = Booking.all
  end

  def create
    @painting = Painting.find(params[:painting_id])
    @booking = Booking.new(booking_params)
    @booking.painting = @painting
    @booking.user = current_user

    if @booking.save
      flash[:notice] = "Your painting has been booked"
      redirect_to paintings_path
    else
      flash[:error] = "Booking unsuccessful"
      render 'paintings/show'
    end
  end

  def confirm
    @booking.confirmed = true
    if @booking.save
      redirect_to painting_path(@painting)
    else
      render "new"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :painting_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def index
    @paintings = Painting.all
  end

  def show
    @painting = Painting.find(params[:id])
    @booking = Booking.new
  end

  def destroy
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(painting_params)
    if @painting.save
      redirect_to painting_path(@painting)
    else
      render :new
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update(painting_params)
      redirect_to painting_path(@painting)
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, end_date)
  end

  def painting_params
    params.require(:painting).permit(:title, :category, :description, :image, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/dashboard.html.erb
<div class="container">
  <div class="title text-center py-3">
    <p class="dashboard-title" >My bookings</p>
    <p>Hi, <%= current_user.email %></p>
  </div>

  <div class="card-columns">
    <% @bookings.each do |booking| %>
    <div class="main_card">
      <div class="card indie_card px-5 py-3">
        <p>You have booked <%= booking.painting.title %> from <%= booking.start_date %> to <%= booking.end_date %></p>
        <img class="card-img-top", src="<%= booking.painting.image %>">
        <p class="pt-3 text-right">created at <%= booking.created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!-- ADDED TWO ROWS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Artsie</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Mansalva&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1524055697392-928c7665644d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1867&q=80">
  <div>
    <h1><strong>Paintings you desire!</strong></h1>
    <p>Whenever you desire</p>
    <div class="text-center">
        <%= link_to "Paintings", paintings_path, class: "btn btn-secondary btn-rounded" %>
    </div>
  </div>
</div>

app/views/paintings/edit.html.erb
<div class="container">
  <div class="col-lg-8 justify-content-center">
    <h1>Edit a Painting</h1>

    <%= simple_form_for(@painting) do |f| %>
    <%= f.input :title %>
    <%= f.input :category %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.submit %>

    <% end %>
  </div>
</div>

app/views/paintings/index.html.erb
<div class="container .bg-light">
  <div class="title text-center">
    <!-- <h1>Artisie</h1> -->
  </div>
  <div class="description pb-2 text-right">
  </div>

  <div class="card-columns">
    <% @paintings.each do |painting| %>
    <%= link_to painting_path(painting) do  %>
    <div class="main_card">
      <div class="card indie_card">
        <%= cl_image_tag painting.image, class: "card-img-top" %>
      </div>
      <p class="text-right"><%= painting.title %></p>
    </div>
    <% end %>
    <% end %>
  </div>

</div>

app/views/paintings/new.html.erb
<div class="container">
  <div class="col-lg-8 justify-content-center">
    <h1>Add a painting</h1>

    <%= simple_form_for(@painting) do |f| %>
    <%= f.input :title %>
    <%= f.input :category %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/paintings/show.html.erb
<div class="container ml-100">
  <div class="row">
    <div class="col-8">
      <div class="card-body">
        <div class="card-show">
          <img src="<%= @painting.image %>" class="card-img-top" alt="@painting.title">
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="my-4 flex-start">
        <h2 class="card-title">
          <%= @painting.title %>
        </h2>
        <p><%= @painting.category %></p>
        <h4><%= @painting.price %> NOK</h4>
        <br>
        <p class="card-text ">
          <%= @painting.description %>
        </p>
      </div>
      <div>
        <!-- Please replace the painting path with booking path when the booking feature is done -->
        <!-- <%#= simple_form_for([@painting, @booking], :url => url_for(:action => 'create', :controller => 'bookings', :method => 'post')) do |f| %> -->
        <%= simple_form_for([@painting, @booking]) do |f| %>
        <div class="dates">
          <div class="form-inputs">
            <div class="form-row">
              <%= f.input :start_date, as: :string, input_html: { class: "datepicker" }, label: "Dates from", placeholder: "yy/mm/dd", wrapper_html: { class: "inline_field_wrapper" } %>
              <%= f.input :end_date, as: :string, input_html: { class: "datepicker" }, label: 'to', placeholder: "yy/mm/dd", wrapper_html: { class: "inline_field_wrapper" } %>
            </div>
          </div>
        </div>
        <div class="form-row">
          <%= f.submit "book", class: "btn btn-secondary btn-lg btn-block btn-booking" %>
        </div>
        <% end %>
        <!-- replace the path with dashboard path -->
        <!-- <%#= link_to "Booking", painting_bookings_path %> -->
      </div>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "Artisie", root_path, class: "logo-link" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="http://localhost:3000/">Home</a> -->
      </li>
      <li class="nav-item">
        <%= link_to "Paintings", paintings_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="http://localhost:3000/paintings">Paintings</a> -->
      </li>
      <li class="nav-item">
        <%= link_to "Add painting", new_painting_path(@painting), class: "nav-link" %>
        <!-- <a class="nav-link" href="http://localhost:3000/">Home</a> -->
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <%= link_to "login", new_user_session_path, class: "nav-link" %>
      <% end %>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>